# Generated by Django 5.1 on 2024-09-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_file_post_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
