# Generated by Django 5.1 on 2024-10-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0006_comment_created_by_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
    ]
