# Generated by Django 5.1 on 2024-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0008_comment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
